import { convert, length } from '..';

test('should return array of unit descriptions for length measure', () => {
  const actual = length.list();
  const expected = [
    {
      abbreviation: 'mm',
      measure: 'length',
      system: 'metric',
      singular: 'millimeter',
      plural: 'millimeters',
    },
    {
      abbreviation: 'cm',
      measure: 'length',
      system: 'metric',
      singular: 'centimeter',
      plural: 'centimeters',
    },
    {
      abbreviation: 'm',
      measure: 'length',
      system: 'metric',
      singular: 'meter',
      plural: 'meters',
    },
    {
      abbreviation: 'km',
      measure: 'length',
      system: 'metric',
      singular: 'kilometer',
      plural: 'kilometers',
    },
    {
      abbreviation: 'in',
      measure: 'length',
      system: 'imperial',
      singular: 'inch',
      plural: 'inches',
    },
    {
      abbreviation: 'hand',
      measure: 'length',
      system: 'imperial',
      singular: 'hand',
      plural: 'hands',
    },
    {
      abbreviation: 'ft',
      measure: 'length',
      system: 'imperial',
      singular: 'foot',
      plural: 'feet',
    },
    {
      abbreviation: 'ft-us',
      measure: 'length',
      system: 'imperial',
      singular: 'US survey foot',
      plural: 'US survey feet',
    },
    {
      abbreviation: 'yd',
      measure: 'length',
      system: 'imperial',
      singular: 'yard',
      plural: 'yards',
    },
    {
      abbreviation: 'fath',
      measure: 'length',
      system: 'imperial',
      singular: 'fathom',
      plural: 'fathoms',
    },
    {
      abbreviation: 'fur',
      measure: 'length',
      system: 'imperial',
      singular: 'furlong',
      plural: 'furlongs',
    },
    {
      abbreviation: 'mi',
      measure: 'length',
      system: 'imperial',
      singular: 'mile',
      plural: 'miles',
    },
    {
      abbreviation: 'nMi',
      measure: 'length',
      system: 'imperial',
      singular: 'international nautical mile',
      plural: 'international nautical miles',
    },
  ];

  expect(actual).toEqual(expected);
});

test('should return array of unit descriptions for illuminance measure', () => {
  const actual = convert.list('illuminance');
  const expected = [
    {
      abbreviation: 'lx',
      measure: 'illuminance',
      system: 'metric',
      singular: 'lux',
      plural: 'lux',
    },
    {
      abbreviation: 'ft-cd',
      measure: 'illuminance',
      system: 'imperial',
      singular: 'foot-candle',
      plural: 'foot-candles',
    },
  ];

  expect(actual).toEqual(expected);
});

test('should return array of unit descriptions for illuminance and pace measures', () => {
  const actual = convert.list('illuminance', 'pace');
  const expected = [
    {
      abbreviation: 'lx',
      measure: 'illuminance',
      system: 'metric',
      singular: 'lux',
      plural: 'lux',
    },
    {
      abbreviation: 'ft-cd',
      measure: 'illuminance',
      system: 'imperial',
      singular: 'foot-candle',
      plural: 'foot-candles',
    },
    {
      abbreviation: 'min/km',
      measure: 'pace',
      system: 'metric',
      singular: 'minute per kilometre',
      plural: 'minutes per kilometre',
    },
    {
      abbreviation: 's/m',
      measure: 'pace',
      system: 'metric',
      singular: 'second per metre',
      plural: 'seconds per metre',
    },
    {
      abbreviation: 'min/mi',
      measure: 'pace',
      system: 'imperial',
      singular: 'minute per mile',
      plural: 'minutes per mile',
    },
    {
      abbreviation: 's/ft',
      measure: 'pace',
      system: 'imperial',
      singular: 'second per foot',
      plural: 'seconds per foot',
    },
  ];

  expect(actual).toEqual(expected);
});

test('should return array of all unit descriptions', () => {
  const actual = convert.list();
  const expected = [
    {
      abbreviation: 'gal',
      measure: 'acceleration',
      system: 'metric',
      singular: 'gal',
      plural: 'gals',
    },
    {
      abbreviation: 'm/s2',
      measure: 'acceleration',
      system: 'metric',
      singular: 'metre per second squared',
      plural: 'metres per second squared',
    },
    {
      abbreviation: 'g-force',
      measure: 'acceleration',
      system: 'metric',
      singular: 'g-force',
      plural: 'g-forces',
    },
    {
      abbreviation: 'rev',
      measure: 'angle',
      system: 'metric',
      singular: 'revolution',
      plural: 'revolutions',
    },
    {
      abbreviation: 'deg',
      measure: 'angle',
      system: 'metric',
      singular: 'degree',
      plural: 'degrees',
    },
    {
      abbreviation: 'rad',
      measure: 'angle',
      system: 'metric',
      singular: 'radian',
      plural: 'radians',
    },
    {
      abbreviation: 'grad',
      measure: 'angle',
      system: 'metric',
      singular: 'gradian',
      plural: 'gradians',
    },
    {
      abbreviation: 'arcmin',
      measure: 'angle',
      system: 'metric',
      singular: 'arcminute',
      plural: 'arcminutes',
    },
    {
      abbreviation: 'arcsec',
      measure: 'angle',
      system: 'metric',
      singular: 'arcsecond',
      plural: 'arcseconds',
    },
    {
      abbreviation: 'mVA',
      measure: 'apparentPower',
      system: 'metric',
      singular: 'millivolt-ampere',
      plural: 'millivolt-amperes',
    },
    {
      abbreviation: 'VA',
      measure: 'apparentPower',
      system: 'metric',
      singular: 'volt-ampere',
      plural: 'volt-amperes',
    },
    {
      abbreviation: 'kVA',
      measure: 'apparentPower',
      system: 'metric',
      singular: 'kilovolt-ampere',
      plural: 'kilovolt-amperes',
    },
    {
      abbreviation: 'MVA',
      measure: 'apparentPower',
      system: 'metric',
      singular: 'megavolt-ampere',
      plural: 'megavolt-amperes',
    },
    {
      abbreviation: 'GVA',
      measure: 'apparentPower',
      system: 'metric',
      singular: 'gigavolt-ampere',
      plural: 'gigavolt-amperes',
    },
    {
      abbreviation: 'mm2',
      measure: 'area',
      system: 'metric',
      singular: 'square millimeter',
      plural: 'square millimeters',
    },
    {
      abbreviation: 'cm2',
      measure: 'area',
      system: 'metric',
      singular: 'square centimeter',
      plural: 'square centimeters',
    },
    {
      abbreviation: 'm2',
      measure: 'area',
      system: 'metric',
      singular: 'square meter',
      plural: 'square meters',
    },
    {
      abbreviation: 'are',
      measure: 'area',
      system: 'metric',
      singular: 'are',
      plural: 'ares',
    },
    {
      abbreviation: 'ha',
      measure: 'area',
      system: 'metric',
      singular: 'hectare',
      plural: 'hectares',
    },
    {
      abbreviation: 'km2',
      measure: 'area',
      system: 'metric',
      singular: 'square kilometer',
      plural: 'square kilometers',
    },
    {
      abbreviation: 'circ-mil',
      measure: 'area',
      system: 'imperial',
      singular: 'circular mil',
      plural: 'circular mils',
    },
    {
      abbreviation: 'circ-inch',
      measure: 'area',
      system: 'imperial',
      singular: 'circular inch',
      plural: 'circular inches',
    },
    {
      abbreviation: 'in2',
      measure: 'area',
      system: 'imperial',
      singular: 'square inch',
      plural: 'square inches',
    },
    {
      abbreviation: 'ft2',
      measure: 'area',
      system: 'imperial',
      singular: 'square foot',
      plural: 'square feet',
    },
    {
      abbreviation: 'yd2',
      measure: 'area',
      system: 'imperial',
      singular: 'square yard',
      plural: 'square yards',
    },
    {
      abbreviation: 'ro',
      measure: 'area',
      system: 'imperial',
      singular: 'rood',
      plural: 'roods',
    },
    {
      abbreviation: 'ac',
      measure: 'area',
      system: 'imperial',
      singular: 'acre',
      plural: 'acres',
    },
    {
      abbreviation: 'mi2',
      measure: 'area',
      system: 'imperial',
      singular: 'square mile',
      plural: 'square miles',
    },
    {
      abbreviation: 'twp',
      measure: 'area',
      system: 'imperial',
      singular: 'township',
      plural: 'townships',
    },
    {
      abbreviation: 'abC',
      measure: 'charge',
      system: 'metric',
      singular: 'abcoulomb',
      plural: 'abcoulombs',
    },
    {
      abbreviation: 'c',
      measure: 'charge',
      system: 'metric',
      singular: 'coulomb',
      plural: 'coulombs',
    },
    {
      abbreviation: 'mC',
      measure: 'charge',
      system: 'metric',
      singular: 'millicoulomb',
      plural: 'millicoulombs',
    },
    {
      abbreviation: 'uC',
      measure: 'charge',
      system: 'metric',
      singular: 'microcoulomb',
      plural: 'microcoulombs',
    },
    {
      abbreviation: 'nC',
      measure: 'charge',
      system: 'metric',
      singular: 'nanocoulomb',
      plural: 'nanocoulombs',
    },
    {
      abbreviation: 'stC',
      measure: 'charge',
      system: 'metric',
      singular: 'statcoulomb',
      plural: 'statcoulombs',
    },
    {
      abbreviation: 'pC',
      measure: 'charge',
      system: 'metric',
      singular: 'picocoulomb',
      plural: 'picocoulombs',
    },
    {
      abbreviation: 'e',
      measure: 'charge',
      system: 'metric',
      singular: 'elementary charge',
      plural: 'elementary charges',
    },
    {
      abbreviation: 'stA',
      measure: 'current',
      system: 'metric',
      singular: 'statampere',
      plural: 'statamperes',
    },
    {
      abbreviation: 'mA',
      measure: 'current',
      system: 'metric',
      singular: 'milliampere',
      plural: 'milliamperes',
    },
    {
      abbreviation: 'A',
      measure: 'current',
      system: 'metric',
      singular: 'ampere',
      plural: 'amperes',
    },
    {
      abbreviation: 'abA',
      measure: 'current',
      system: 'metric',
      singular: 'abampere',
      plural: 'abamperes',
    },
    {
      abbreviation: 'kA',
      measure: 'current',
      system: 'metric',
      singular: 'kiloampere',
      plural: 'kiloamperes',
    },
    {
      abbreviation: 'b',
      measure: 'digital',
      system: 'bits',
      singular: 'bit',
      plural: 'bits',
    },
    {
      abbreviation: 'Kb',
      measure: 'digital',
      system: 'bits',
      singular: 'kilobit',
      plural: 'kilobits',
    },
    {
      abbreviation: 'Mb',
      measure: 'digital',
      system: 'bits',
      singular: 'megabit',
      plural: 'megabits',
    },
    {
      abbreviation: 'Gb',
      measure: 'digital',
      system: 'bits',
      singular: 'gigabit',
      plural: 'gigabits',
    },
    {
      abbreviation: 'Tb',
      measure: 'digital',
      system: 'bits',
      singular: 'terabit',
      plural: 'terabits',
    },
    {
      abbreviation: 'B',
      measure: 'digital',
      system: 'bytes',
      singular: 'byte',
      plural: 'bytes',
    },
    {
      abbreviation: 'KB',
      measure: 'digital',
      system: 'bytes',
      singular: 'kilobyte',
      plural: 'kilobytes',
    },
    {
      abbreviation: 'MB',
      measure: 'digital',
      system: 'bytes',
      singular: 'megabyte',
      plural: 'megabytes',
    },
    {
      abbreviation: 'GB',
      measure: 'digital',
      system: 'bytes',
      singular: 'gigabyte',
      plural: 'gigabytes',
    },
    {
      abbreviation: 'TB',
      measure: 'digital',
      system: 'bytes',
      singular: 'terabyte',
      plural: 'terabytes',
    },
    {
      abbreviation: 'J',
      measure: 'energy',
      system: 'metric',
      singular: 'joule',
      plural: 'joules',
    },
    {
      abbreviation: 'kJ',
      measure: 'energy',
      system: 'metric',
      singular: 'kilojoule',
      plural: 'kilojoules',
    },
    {
      abbreviation: 'mWh',
      measure: 'energy',
      system: 'metric',
      singular: 'milliwatt-hour',
      plural: 'milliwatt-hours',
    },
    {
      abbreviation: 'Wh',
      measure: 'energy',
      system: 'metric',
      singular: 'watt-hour',
      plural: 'watt-hours',
    },
    {
      abbreviation: 'kWh',
      measure: 'energy',
      system: 'metric',
      singular: 'kilowatt-hour',
      plural: 'kilowatt-hours',
    },
    {
      abbreviation: 'MWh',
      measure: 'energy',
      system: 'metric',
      singular: 'megawatt-hour',
      plural: 'megawatt-hours',
    },
    {
      abbreviation: 'GWh',
      measure: 'energy',
      system: 'metric',
      singular: 'gigawatt-hour',
      plural: 'gigawatt-hours',
    },
    {
      abbreviation: 'Btu-it',
      measure: 'energy',
      system: 'imperial',
      singular: 'british thermal unit (international table)',
      plural: 'british thermal units (international table)',
    },
    {
      abbreviation: 'N',
      measure: 'force',
      system: 'metric',
      singular: 'newton',
      plural: 'newtons',
    },
    {
      abbreviation: 'kN',
      measure: 'force',
      system: 'metric',
      singular: 'kilonewton',
      plural: 'kilonewtons',
    },
    {
      abbreviation: 'lbf',
      measure: 'force',
      system: 'imperial',
      singular: 'pound-force',
      plural: 'pound-forces',
    },
    {
      abbreviation: 'mHz',
      measure: 'frequency',
      system: 'metric',
      singular: 'millihertz',
      plural: 'millihertz',
    },
    {
      abbreviation: 'Hz',
      measure: 'frequency',
      system: 'metric',
      singular: 'hertz',
      plural: 'hertz',
    },
    {
      abbreviation: 'kHz',
      measure: 'frequency',
      system: 'metric',
      singular: 'kilohertz',
      plural: 'kilohertz',
    },
    {
      abbreviation: 'MHz',
      measure: 'frequency',
      system: 'metric',
      singular: 'megahertz',
      plural: 'megahertz',
    },
    {
      abbreviation: 'GHz',
      measure: 'frequency',
      system: 'metric',
      singular: 'gigahertz',
      plural: 'gigahertz',
    },
    {
      abbreviation: 'THz',
      measure: 'frequency',
      system: 'metric',
      singular: 'terahertz',
      plural: 'terahertz',
    },
    {
      abbreviation: 'rpm',
      measure: 'frequency',
      system: 'metric',
      singular: 'rotation per minute',
      plural: 'rotations per minute',
    },
    {
      abbreviation: 'deg/s',
      measure: 'frequency',
      system: 'metric',
      singular: 'degree per second',
      plural: 'degrees per second',
    },
    {
      abbreviation: 'rad/s',
      measure: 'frequency',
      system: 'metric',
      singular: 'radian per second',
      plural: 'radians per second',
    },
    {
      abbreviation: 'lx',
      measure: 'illuminance',
      system: 'metric',
      singular: 'lux',
      plural: 'lux',
    },
    {
      abbreviation: 'ft-cd',
      measure: 'illuminance',
      system: 'imperial',
      singular: 'foot-candle',
      plural: 'foot-candles',
    },
    {
      abbreviation: 'mm',
      measure: 'length',
      system: 'metric',
      singular: 'millimeter',
      plural: 'millimeters',
    },
    {
      abbreviation: 'cm',
      measure: 'length',
      system: 'metric',
      singular: 'centimeter',
      plural: 'centimeters',
    },
    {
      abbreviation: 'm',
      measure: 'length',
      system: 'metric',
      singular: 'meter',
      plural: 'meters',
    },
    {
      abbreviation: 'km',
      measure: 'length',
      system: 'metric',
      singular: 'kilometer',
      plural: 'kilometers',
    },
    {
      abbreviation: 'in',
      measure: 'length',
      system: 'imperial',
      singular: 'inch',
      plural: 'inches',
    },
    {
      abbreviation: 'hand',
      measure: 'length',
      system: 'imperial',
      singular: 'hand',
      plural: 'hands',
    },
    {
      abbreviation: 'ft',
      measure: 'length',
      system: 'imperial',
      singular: 'foot',
      plural: 'feet',
    },
    {
      abbreviation: 'ft-us',
      measure: 'length',
      system: 'imperial',
      singular: 'US survey foot',
      plural: 'US survey feet',
    },
    {
      abbreviation: 'yd',
      measure: 'length',
      system: 'imperial',
      singular: 'yard',
      plural: 'yards',
    },
    {
      abbreviation: 'fath',
      measure: 'length',
      system: 'imperial',
      singular: 'fathom',
      plural: 'fathoms',
    },
    {
      abbreviation: 'fur',
      measure: 'length',
      system: 'imperial',
      singular: 'furlong',
      plural: 'furlongs',
    },
    {
      abbreviation: 'mi',
      measure: 'length',
      system: 'imperial',
      singular: 'mile',
      plural: 'miles',
    },
    {
      abbreviation: 'nMi',
      measure: 'length',
      system: 'imperial',
      singular: 'international nautical mile',
      plural: 'international nautical miles',
    },
    {
      abbreviation: 'mg',
      measure: 'mass',
      system: 'metric',
      singular: 'milligram',
      plural: 'milligrams',
    },
    {
      abbreviation: 'g',
      measure: 'mass',
      system: 'metric',
      singular: 'gram',
      plural: 'grams',
    },
    {
      abbreviation: 'kg',
      measure: 'mass',
      system: 'metric',
      singular: 'kilogram',
      plural: 'kilograms',
    },
    {
      abbreviation: 't',
      measure: 'mass',
      system: 'metric',
      singular: 'ton',
      plural: 'tons',
    },
    {
      abbreviation: 'kt',
      measure: 'mass',
      system: 'metric',
      singular: 'kiloton',
      plural: 'kilotons',
    },
    {
      abbreviation: 'mt',
      measure: 'mass',
      system: 'metric',
      singular: 'megaton',
      plural: 'megatons',
    },
    {
      abbreviation: 'gr',
      measure: 'mass',
      system: 'imperial',
      singular: 'grain',
      plural: 'grains',
    },
    {
      abbreviation: 'dr',
      measure: 'mass',
      system: 'imperial',
      singular: 'dram',
      plural: 'drams',
    },
    {
      abbreviation: 'oz',
      measure: 'mass',
      system: 'imperial',
      singular: 'ounce',
      plural: 'ounces',
    },
    {
      abbreviation: 'lb',
      measure: 'mass',
      system: 'imperial',
      singular: 'pound',
      plural: 'pounds',
    },
    {
      abbreviation: 'stone',
      measure: 'mass',
      system: 'imperial',
      singular: 'stone',
      plural: 'stones',
    },
    {
      abbreviation: 'qr',
      measure: 'mass',
      system: 'imperial',
      singular: 'quarter',
      plural: 'quarters',
    },
    {
      abbreviation: 'slug',
      measure: 'mass',
      system: 'imperial',
      singular: 'slug',
      plural: 'slugs',
    },
    {
      abbreviation: 'tn',
      measure: 'mass',
      system: 'imperial',
      singular: 'short ton',
      plural: 'short tons',
    },
    {
      abbreviation: 'ton-uk',
      measure: 'mass',
      system: 'imperial',
      singular: 'imperial ton',
      plural: 'imperial tons',
    },
    {
      abbreviation: 'min/km',
      measure: 'pace',
      system: 'metric',
      singular: 'minute per kilometre',
      plural: 'minutes per kilometre',
    },
    {
      abbreviation: 's/m',
      measure: 'pace',
      system: 'metric',
      singular: 'second per metre',
      plural: 'seconds per metre',
    },
    {
      abbreviation: 'min/mi',
      measure: 'pace',
      system: 'imperial',
      singular: 'minute per mile',
      plural: 'minutes per mile',
    },
    {
      abbreviation: 's/ft',
      measure: 'pace',
      system: 'imperial',
      singular: 'second per foot',
      plural: 'seconds per foot',
    },
    {
      abbreviation: 'mW',
      measure: 'power',
      system: 'metric',
      singular: 'milliwatt',
      plural: 'milliwatts',
    },
    {
      abbreviation: 'W',
      measure: 'power',
      system: 'metric',
      singular: 'watt',
      plural: 'watts',
    },
    {
      abbreviation: 'kW',
      measure: 'power',
      system: 'metric',
      singular: 'kilowatt',
      plural: 'kilowatts',
    },
    {
      abbreviation: 'MW',
      measure: 'power',
      system: 'metric',
      singular: 'megawatt',
      plural: 'megawatts',
    },
    {
      abbreviation: 'GW',
      measure: 'power',
      system: 'metric',
      singular: 'gigawatt',
      plural: 'gigawatts',
    },
    {
      abbreviation: 'Pa',
      measure: 'pressure',
      system: 'metric',
      singular: 'pascal',
      plural: 'pascals',
    },
    {
      abbreviation: 'hPa',
      measure: 'pressure',
      system: 'metric',
      singular: 'hectopascal',
      plural: 'hectopascals',
    },
    {
      abbreviation: 'kPa',
      measure: 'pressure',
      system: 'metric',
      singular: 'kilopascal',
      plural: 'kilopascals',
    },
    {
      abbreviation: 'bar',
      measure: 'pressure',
      system: 'metric',
      singular: 'bar',
      plural: 'bars',
    },
    {
      abbreviation: 'MPa',
      measure: 'pressure',
      system: 'metric',
      singular: 'megapascal',
      plural: 'megapascals',
    },
    {
      abbreviation: 'torr',
      measure: 'pressure',
      system: 'metric',
      singular: 'torr',
      plural: 'torr',
    },
    {
      abbreviation: 'psi',
      measure: 'pressure',
      system: 'imperial',
      singular: 'pound per square inch',
      plural: 'pounds per square inch',
    },
    {
      abbreviation: 'ksi',
      measure: 'pressure',
      system: 'imperial',
      singular: 'kilopound per square inch',
      plural: 'kilopound per square inch',
    },
    {
      abbreviation: 'mVARh',
      measure: 'reactiveEnergy',
      system: 'metric',
      singular: 'millivolt-ampere reactive hour',
      plural: 'millivolt-amperes reactive hour',
    },
    {
      abbreviation: 'VARh',
      measure: 'reactiveEnergy',
      system: 'metric',
      singular: 'volt-ampere reactive hour',
      plural: 'volt-amperes reactive hour',
    },
    {
      abbreviation: 'kVARh',
      measure: 'reactiveEnergy',
      system: 'metric',
      singular: 'kilovolt-ampere reactive hour',
      plural: 'kilovolt-amperes reactive hour',
    },
    {
      abbreviation: 'MVARh',
      measure: 'reactiveEnergy',
      system: 'metric',
      singular: 'megavolt-ampere reactive hour',
      plural: 'megavolt-amperes reactive hour',
    },
    {
      abbreviation: 'GVARh',
      measure: 'reactiveEnergy',
      system: 'metric',
      singular: 'gigavolt-ampere reactive hour',
      plural: 'gigavolt-amperes reactive hour',
    },
    {
      abbreviation: 'mVAR',
      measure: 'reactivePower',
      system: 'metric',
      singular: 'millivolt-ampere reactive',
      plural: 'millivolt-amperes reactive',
    },
    {
      abbreviation: 'VAR',
      measure: 'reactivePower',
      system: 'metric',
      singular: 'volt-ampere reactive',
      plural: 'volt-amperes reactive',
    },
    {
      abbreviation: 'kVAR',
      measure: 'reactivePower',
      system: 'metric',
      singular: 'kilovolt-ampere reactive',
      plural: 'kilovolt-amperes reactive',
    },
    {
      abbreviation: 'MVAR',
      measure: 'reactivePower',
      system: 'metric',
      singular: 'megavolt-ampere reactive',
      plural: 'megavolt-amperes reactive',
    },
    {
      abbreviation: 'GVAR',
      measure: 'reactivePower',
      system: 'metric',
      singular: 'gigavolt-ampere reactive',
      plural: 'gigavolt-amperes reactive',
    },
    {
      abbreviation: 'km/h',
      measure: 'speed',
      system: 'metric',
      singular: 'kilometre per hour',
      plural: 'kilometres per hour',
    },
    {
      abbreviation: 'm/s',
      measure: 'speed',
      system: 'metric',
      singular: 'metre per second',
      plural: 'metres per second',
    },
    {
      abbreviation: 'ft/s',
      measure: 'speed',
      system: 'imperial',
      singular: 'foot per second',
      plural: 'feet per second',
    },
    {
      abbreviation: 'mi/h',
      measure: 'speed',
      system: 'imperial',
      singular: 'mile per hour',
      plural: 'miles per hour',
    },
    {
      abbreviation: 'knot',
      measure: 'speed',
      system: 'imperial',
      singular: 'knot',
      plural: 'knots',
    },
    {
      abbreviation: 'C',
      measure: 'temperature',
      system: 'metric',
      singular: 'degree celsius',
      plural: 'degrees celsius',
    },
    {
      abbreviation: 'K',
      measure: 'temperature',
      system: 'metric',
      singular: 'degree kelvin',
      plural: 'degrees kelvin',
    },
    {
      abbreviation: 'F',
      measure: 'temperature',
      system: 'imperial',
      singular: 'degree fahrenheit',
      plural: 'degrees fahrenheit',
    },
    {
      abbreviation: 'R',
      measure: 'temperature',
      system: 'imperial',
      singular: 'degree rankine',
      plural: 'degrees rankine',
    },
    {
      abbreviation: 'ns',
      measure: 'time',
      system: 'metric',
      singular: 'nanosecond',
      plural: 'nanoseconds',
    },
    {
      abbreviation: 'mu',
      measure: 'time',
      system: 'metric',
      singular: 'microsecond',
      plural: 'microseconds',
    },
    {
      abbreviation: 'ms',
      measure: 'time',
      system: 'metric',
      singular: 'millisecond',
      plural: 'milliseconds',
    },
    {
      abbreviation: 's',
      measure: 'time',
      system: 'metric',
      singular: 'second',
      plural: 'seconds',
    },
    {
      abbreviation: 'min',
      measure: 'time',
      system: 'metric',
      singular: 'minute',
      plural: 'minutes',
    },
    {
      abbreviation: 'h',
      measure: 'time',
      system: 'metric',
      singular: 'hour',
      plural: 'hours',
    },
    {
      abbreviation: 'd',
      measure: 'time',
      system: 'metric',
      singular: 'day',
      plural: 'days',
    },
    {
      abbreviation: 'week',
      measure: 'time',
      system: 'metric',
      singular: 'week',
      plural: 'weeks',
    },
    {
      abbreviation: 'fortnight',
      measure: 'time',
      system: 'metric',
      singular: 'fortnight',
      plural: 'fortnights',
    },
    {
      abbreviation: 'month',
      measure: 'time',
      system: 'metric',
      singular: 'month',
      plural: 'months',
    },
    {
      abbreviation: 'year',
      measure: 'time',
      system: 'metric',
      singular: 'year',
      plural: 'years',
    },
    {
      abbreviation: 'mV',
      measure: 'voltage',
      system: 'metric',
      singular: 'millivolt',
      plural: 'millivolts',
    },
    {
      abbreviation: 'V',
      measure: 'voltage',
      system: 'metric',
      singular: 'volt',
      plural: 'volts',
    },
    {
      abbreviation: 'kV',
      measure: 'voltage',
      system: 'metric',
      singular: 'kilovolt',
      plural: 'kilovolts',
    },
    {
      abbreviation: 'mm3',
      measure: 'volume',
      system: 'metric',
      singular: 'cubic millimeter',
      plural: 'cubic millimeters',
    },
    {
      abbreviation: 'cm3',
      measure: 'volume',
      system: 'metric',
      singular: 'cubic centimeter',
      plural: 'cubic centimeters',
    },
    {
      abbreviation: 'ml',
      measure: 'volume',
      system: 'metric',
      singular: 'millilitre',
      plural: 'millilitres',
    },
    {
      abbreviation: 'cl',
      measure: 'volume',
      system: 'metric',
      singular: 'centilitre',
      plural: 'centilitres',
    },
    {
      abbreviation: 'dl',
      measure: 'volume',
      system: 'metric',
      singular: 'decilitre',
      plural: 'decilitres',
    },
    {
      abbreviation: 'l',
      measure: 'volume',
      system: 'metric',
      singular: 'litre',
      plural: 'litres',
    },
    {
      abbreviation: 'kl',
      measure: 'volume',
      system: 'metric',
      singular: 'kilolitre',
      plural: 'kilolitres',
    },
    {
      abbreviation: 'm3',
      measure: 'volume',
      system: 'metric',
      singular: 'cubic meter',
      plural: 'cubic meters',
    },
    {
      abbreviation: 'km3',
      measure: 'volume',
      system: 'metric',
      singular: 'cubic kilometer',
      plural: 'cubic kilometers',
    },
    {
      abbreviation: 'krm',
      measure: 'volume',
      system: 'metric',
      singular: 'kryddmått',
      plural: 'kryddmåtten',
    },
    {
      abbreviation: 'tsk',
      measure: 'volume',
      system: 'metric',
      singular: 'tesked',
      plural: 'teskedar',
    },
    {
      abbreviation: 'msk',
      measure: 'volume',
      system: 'metric',
      singular: 'matsked',
      plural: 'matskedar',
    },
    {
      abbreviation: 'kkp',
      measure: 'volume',
      system: 'metric',
      singular: 'kaffekopp',
      plural: 'kaffekoppar',
    },
    {
      abbreviation: 'glas',
      measure: 'volume',
      system: 'metric',
      singular: 'glas',
      plural: 'glas',
    },
    {
      abbreviation: 'kanna',
      measure: 'volume',
      system: 'metric',
      singular: 'kanna',
      plural: 'kannor',
    },
    {
      abbreviation: 'tsp',
      measure: 'volume',
      system: 'imperial',
      singular: 'teaspoon',
      plural: 'teaspoons',
    },
    {
      abbreviation: 'Tbs',
      measure: 'volume',
      system: 'imperial',
      singular: 'tablespoon',
      plural: 'tablespoons',
    },
    {
      abbreviation: 'in3',
      measure: 'volume',
      system: 'imperial',
      singular: 'cubic inch',
      plural: 'cubic inches',
    },
    {
      abbreviation: 'fl-oz',
      measure: 'volume',
      system: 'imperial',
      singular: 'fluid ounce',
      plural: 'fluid ounces',
    },
    {
      abbreviation: 'cup',
      measure: 'volume',
      system: 'imperial',
      singular: 'cup',
      plural: 'cups',
    },
    {
      abbreviation: 'pnt',
      measure: 'volume',
      system: 'imperial',
      singular: 'pint',
      plural: 'pints',
    },
    {
      abbreviation: 'qt',
      measure: 'volume',
      system: 'imperial',
      singular: 'quart',
      plural: 'quarts',
    },
    {
      abbreviation: 'gal',
      measure: 'volume',
      system: 'imperial',
      singular: 'gallon',
      plural: 'gallons',
    },
    {
      abbreviation: 'ft3',
      measure: 'volume',
      system: 'imperial',
      singular: 'cubic foot',
      plural: 'cubic feet',
    },
    {
      abbreviation: 'yd3',
      measure: 'volume',
      system: 'imperial',
      singular: 'cubic yard',
      plural: 'cubic yards',
    },
    {
      abbreviation: 'mm3/s',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'cubic millimeter per second',
      plural: 'cubic millimeters per second',
    },
    {
      abbreviation: 'cm3/s',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'cubic centimeter per second',
      plural: 'cubic centimeters per second',
    },
    {
      abbreviation: 'ml/s',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'millilitre per second',
      plural: 'millilitres per second',
    },
    {
      abbreviation: 'cl/s',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'centilitre per second',
      plural: 'centilitres per second',
    },
    {
      abbreviation: 'dl/s',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'decilitre per second',
      plural: 'decilitres per second',
    },
    {
      abbreviation: 'l/s',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'litre per second',
      plural: 'litres per second',
    },
    {
      abbreviation: 'l/min',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'litre per minute',
      plural: 'litres per minute',
    },
    {
      abbreviation: 'l/h',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'litre per hour',
      plural: 'litres per hour',
    },
    {
      abbreviation: 'kl/s',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'kilolitre per second',
      plural: 'kilolitres per second',
    },
    {
      abbreviation: 'kl/min',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'kilolitre per minute',
      plural: 'kilolitres per minute',
    },
    {
      abbreviation: 'kl/h',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'kilolitre per hour',
      plural: 'kilolitres per hour',
    },
    {
      abbreviation: 'm3/s',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'cubic meter per second',
      plural: 'cubic meters per second',
    },
    {
      abbreviation: 'm3/min',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'cubic meter per minute',
      plural: 'cubic meters per minute',
    },
    {
      abbreviation: 'm3/h',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'cubic meter per hour',
      plural: 'cubic meters per hour',
    },
    {
      abbreviation: 'km3/s',
      measure: 'volumeFlowRate',
      system: 'metric',
      singular: 'cubic kilometer per second',
      plural: 'cubic kilometers per second',
    },
    {
      abbreviation: 'tsp/s',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'teaspoon per second',
      plural: 'teaspoons per second',
    },
    {
      abbreviation: 'Tbs/s',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'tablespoon per second',
      plural: 'tablespoons per second',
    },
    {
      abbreviation: 'in3/s',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'cubic inch per second',
      plural: 'cubic inches per second',
    },
    {
      abbreviation: 'in3/min',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'cubic inch per minute',
      plural: 'cubic inches per minute',
    },
    {
      abbreviation: 'in3/h',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'cubic inch per hour',
      plural: 'cubic inches per hour',
    },
    {
      abbreviation: 'fl-oz/s',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'fluid ounce per second',
      plural: 'fluid ounces per second',
    },
    {
      abbreviation: 'fl-oz/min',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'fluid ounce per minute',
      plural: 'fluid ounces per minute',
    },
    {
      abbreviation: 'fl-oz/h',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'fluid ounce per hour',
      plural: 'fluid ounces per hour',
    },
    {
      abbreviation: 'cup/s',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'cup per second',
      plural: 'cups per second',
    },
    {
      abbreviation: 'pnt/s',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'pint per second',
      plural: 'pints per second',
    },
    {
      abbreviation: 'pnt/min',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'pint per minute',
      plural: 'pints per minute',
    },
    {
      abbreviation: 'pnt/h',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'pint per hour',
      plural: 'pints per hour',
    },
    {
      abbreviation: 'qt/s',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'quart per second',
      plural: 'quarts per second',
    },
    {
      abbreviation: 'gal/s',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'gallon per second',
      plural: 'gallons per second',
    },
    {
      abbreviation: 'gal/min',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'gallon per minute',
      plural: 'gallons per minute',
    },
    {
      abbreviation: 'gal/h',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'gallon per hour',
      plural: 'gallons per hour',
    },
    {
      abbreviation: 'ft3/s',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'cubic foot per second',
      plural: 'cubic feet per second',
    },
    {
      abbreviation: 'ft3/min',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'cubic foot per minute',
      plural: 'cubic feet per minute',
    },
    {
      abbreviation: 'ft3/h',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'cubic foot per hour',
      plural: 'cubic feet per hour',
    },
    {
      abbreviation: 'yd3/s',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'cubic yard per second',
      plural: 'cubic yards per second',
    },
    {
      abbreviation: 'yd3/min',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'cubic yard per minute',
      plural: 'cubic yards per minute',
    },
    {
      abbreviation: 'yd3/h',
      measure: 'volumeFlowRate',
      system: 'imperial',
      singular: 'cubic yard per hour',
      plural: 'cubic yards per hour',
    },
  ];

  expect(actual).toEqual(expected);
});
